second app/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'armstrong/input'
  get 'armstrong', to: redirect('armstrong/input')
  get 'armstrong/result', as: :result_armstrong

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

second app/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

second app/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

second app/app/controllers/armstrong_controller.rb
# frozen_string_literal: true
require 'active_support/all'
require 'net/http'
require 'nokogiri'


class ArmstrongController < ApplicationController
  def input; end

  def result
    uri = URI("http://localhost:3000/armstrong/result.xml?number=#{params[:number]}")
    xml= Net::HTTP.get(uri)
    doc = Nokogiri::XML(xml)
    if params[:format_disp] == 'html'
      xslt = Nokogiri::XSLT(File.read('public/basic_transformer.xslt'))
      @html = xslt.transform(doc).to_s
    else
      pi = Nokogiri::XML::ProcessingInstruction.new(doc, "xml-stylesheet",
                                                    'type="text/xml" href="/client_transformer.xslt"')
      doc.root.add_previous_sibling pi
      render :xml => doc
    end
  end
end

second app/app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

second app/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

second app/app/helpers/armstrong_helper.rb
# frozen_string_literal: true

module ArmstrongHelper
end

second app/app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

second app/app/views/armstrong/input.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4" align="center">
      <h1>Armstrong numbers</h1>
      <%= bootstrap_form_tag url: result_armstrong_path, method: 'get' do |f| %>
        <%= f.number_field :number, label: 'Number of digits in number'%>
        <%= f.form_group :format_disp do %>
          <%= f.radio_button :format_disp, 'html', label: 'html', inline: true, checked: true %>
          <%= f.radio_button :format_disp, 'xml', label: 'xml', inline: true %>
        <% end %>

        <%= f.primary 'Show numbers'%>
      <% end %>
    </div>
  </div>
</div>

second app/app/views/armstrong/result.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3" align="center">
      <%== @html %>
      <%= content_tag 'a', 'Go back', role: 'button', class: 'btn btn-primary', href: armstrong_path %>
    </div>
  </div>
</div>

second app/app/views/layouts/_footer.html.erb
<footer>
  <span class="text-muted">Eliseev Vyacheslav, 2018</span>
</footer>

second app/app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <!-- Brand/logo -->
    <%= content_tag :a, 'Armstrong', class: 'navbar-brand', href: root_path %>

    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= content_tag :a, 'Calculate', class: 'nav-link', href: armstrong_path %>
      </li>
    </ul>
  </nav>
</header>

second app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lr10</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



  </head>

  <body class="bg-light">
    <%= render 'layouts/header' %>
    <main class="container" role="main">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

second app/app/views/welcome/index.html.erb
<div class="container" align="center">
  <div class="row">
    <div class="col-md-8 offset-md-2 center">
      <h1>Armstrong number</h1>
      <div class="jumbotron">
        In recreational number theory, a narcissistic number (also known as a pluperfect digital invariant (PPDI), an Armstrong number (after Michael F. Armstrong) or a plus perfect number) is a number that is the sum of its own digits each raised to the power of the number of digits. This definition depends on the base b of the number system used, e.g., b = 10 for the decimal system or b = 2 for the binary system.
      </div>
      <%= content_tag 'a', "Let's calculate some of them", role: 'button', class: 'btn btn-primary', href: armstrong_path %>
    </div>
  </div>
</div>